# Requires that ~/.fog have aws_access_key_id and aws_secret_access_key
HOSTS:
  "puppet":
    roles:
      - "master"
      - "default"
    vmname: "centos-7-x86-64-west"
    hypervisor: "ec2"
    platform: "el-7-x86_64"
    snapshot: "ebs"
    amisize: m5.xlarge
    user: centos
  "netscaler":
    roles:
      - "netscaler"
    vmname: "netscaler-premium-13.0-10mb"
    hypervisor: "ec2"
    platform: "netscaler-10.5-55.8"
    snapshot: "default"
    amisize: "m5.large"
    user: "nsroot"
    ssh:
      password: 'nsroot'
    additional_ports: 443
CONFIG:
  type: "aio"
  puppet_collection: puppet6
  ec2_yaml: "spec/acceptance/nodesets/ec2.yaml"
  log_level: "debug"
  ssh:
    keys: "~/.ssh/id_rsa-acceptance"
  datastore: "instance0"
  folder: "Delivery/Quality Assurance/Enterprise/Dynamic"
  resourcepool: "delivery/Quality Assurance/Enterprise/Dynamic"
  pooling_api: "http://vcloud.delivery.puppetlabs.net/"
